import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jon Bruckman's Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">Jon Bruckman</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 ml-8 rounded-md"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Jon Bruckman
            </h2>
            <h3 className="text-2xl py-2">Full Stack Engineer</h3>
            <p classname="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">
              I'm a Full Stack Software Engineer out of Cleveland Ohio. I am
              passionate in creating elegant solutions to complex problems
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-500">
            <a href="https://twitter.com/JonBruckmanDev">
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.linkedin.com/in/jonathanbruckman/">
              <AiFillLinkedin />
            </a>
            <a href="https://www.youtube.com/channel/UCUSuVA5gjt1QXHrQAu4AYSA">
              <AiFillYoutube />
            </a>
          </div>
        </section>
      </main>
    </div>
  );
}
